# Generated by Django 4.2.10 on 2024-02-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='name',
            new_name='search_bar',
        ),
    ]
