# Generated by Django 4.2.10 on 2024-02-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_search_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('groups', 'groups')], default='books', max_length=10),
        ),
    ]
