# Generated by Django 4.2.10 on 2024-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_group_categories_alter_group_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numbers_of_ratings',
            field=models.CharField(max_length=50, null=True, verbose_name='number of ratings'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numbers_of_reviews',
            field=models.CharField(max_length=50, null=True, verbose_name='number of reviews'),
        ),
    ]
