# Generated by Django 4.2.10 on 2024-02-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_book_numbers_of_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.JSONField(default=list, null=True, verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_format',
            field=models.CharField(max_length=100, null=True, verbose_name='pages format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_info',
            field=models.TextField(null=True, verbose_name='publication_info'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.CharField(max_length=10, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
